### ISSUE TITLE
Add the ability to query pieces of a URL using like statement or something similar...

### ISSUE THREAD

**Issue by seandoesgis** [dvrpc/api_tracker#2]
It'd be nice to query the list of APIs based on pieces of a URL if need be.  

ie. GIS services can reside on difference servers and it'd be good to use this to find all apps using services from arcgis.dvrpc.org, tiles.dvrpc.org, services1.arcgis.com

**Comment by kdwarn** [comment]
@seandoesgis This is how it works, though I'll add a readme so people actually know how it works. :) Front end will likely say that too once it's built.
